# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
changelog:
  categories:
    - title: New features
      labels:
        - feature
    - title: Improvements
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - fix
        - field issue
    - title: Miscellaneous
      labels:
        - dependencies
        - ci
        - documentation
        - sidecar
