apiVersion: v2
name: csi-wekafsplugin
description: Helm chart for Deployment of WekaIO Container Storage Interface (CSI) plugin for WekaFS - the world fastest filesystem
maintainers:
  - name: WekaIO, Inc.
    email: csi@weka.io
    url: https://weka.io
sources:
  - https://github.com/weka/csi-wekafs/tree/$VERSION
home: https://github.com/weka/csi-wekafs
icon: https://weka.github.io/csi-wekafs/logo.png
type: application
version: 2.0.0
appVersion: 2.0.0
kubeVersion: ">=1.18.0"
keywords: [storage, filesystem, HPC]
annotations:
  artifacthub.io/category: "storage"
  artifacthub.io/prerelease: "false"
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/license: Apache-2.0
