name: draft

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: main
          target_commitish: main
          generate_release_notes: true
          name: DRAFT
