name: draft

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0

      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: master
          target_commitish: master
          generate_release_notes: true
          name: DRAFT
